#pragma once

typedef struct _SLOT_USER_DATA
{
	WCHAR		USER_ID[32];
	DWORD_PTR	SESSION_ID;
	WCHAR		VIRTUAL_ADDRESS[32];
	USHORT		VIRTUAL_PORT;
	WCHAR		REAL_ADDRESS[32];
	USHORT		REAL_PORT;
	BOOL		ISREADY;

	_SLOT_USER_DATA()
	{
		SESSION_ID = 0;
	}
} SLOT_USER_DATA;

typedef enum TCP_PROTOCOL
{
	PT_VERSION	= 0x1000000,


	PT_LOBY_ENTER,
	/*
	WCHAR			:	USER_ID[32]
	WCHAR			:	VIRTUAL_ADDRESS[32]
	USHORT			:	VIRTUAL_PORT
	*/

	PT_LOBY_ENTER_SUCC_U,
	/*
	WCHAR			:	USER_ID[32]
	DWORD_PTR		:	SESSION_ID
	WCHAR			:	VIRTUAL_ADDRESS[32]
	USHORT			:	VIRTUAL_PORT
	WCHAR			:	REAL_ADDRESS[32]
	USHORT			:	REAL_PORT
	*/
	PT_ROOM_LEAVE,
	/*
	*/
	PT_ROOM_LEAVE_SUCC_U,
	/*
	*/
	PT_ROOM_LEAVE_M,
	/*
	DWORD_PTR		:	SESSION_ID
	DWORD_PTR		:	MASTERSESSION_ID
	*/
	PT_CREATE_ROOM,
	/*
	WCHAR			:	TITLE[32]
	*/
	PT_CREATE_ROOM_SUCC_U,
	/*
	USHORT			:	SLOT_IDX
	WCHAR			:	TITLE[32]
	*/
	PT_ROOMLIST_ERASE_M,
	/*
	USHORT			:	ROOM_IDX		
	*/
	PT_ROOMLIST_RENEWAL,
	/*
	*/
	PT_ROOMLIST_RENEWAL_M,
	/*
	WCHAR			:	TITLE[32]
	DWORD_PTR		:	MASTERSESSION_ID
	USHORT			:	ROOM_IDX		
	*/
	PT_ROOM_ENTER,
	/*
	USHORT			:	ROOM_IDX
	*/
	PT_ROOM_ENTER_SUCC_U,
	/*
	WCHAR			:	TITLE[32]
	SLOT_USER_DATA	:	ROOM_USER_INFO[8]
	*/
	PT_ROOM_USER_ENTRY_M,
	/*
	WCHAR			:	USER_ID[32]
	DWORD_PTR		:	SESSION_ID
	WCHAR			:	VIRTUAL_ADDRESS[32]
	USHORT			:	VIRTUAL_PORT
	WCHAR			:	REAL_ADDRESS[32]
	USHORT			:	REAL_PORT
	USHORT			:	SLOT_DIX
	*/
	PT_ROOM_SENDCHAT,
	/*
	WCHAR			:	USER_ID[32]
	WCHAR			:	MESSAGE[32]
	DWORD_PTR		:	SESSION_ID
	*/
	PT_ROOM_RECEIVE_CHAT_M,
	/*
	WCHAR			:	USER_ID[32]
	WCHAR			:	MESSAGE[32]
	DWORD_PTR		:	SESSION_ID
	*/
	PT_END
};