#pragma once

typedef struct _S_PU_C2S_TUNNELING
{
	DWORD_PTR SESSION_ID;
	WCHAR REMOTE_ADDRESS[32];
	USHORT REMOTE_PORT;
} S_PU_C2S_TUNNELING;

typedef struct _S_PU_S2C_TUNNELING_SUCC_U
{
} S_PU_S2C_TUNNELING_SUCC_U;

typedef struct _S_PU_S2C_TUNNELING_FAIL_U
{
	DWORD ERROR_CODE;
} S_PU_S2C_TUNNELING_FAIL_U;

typedef struct _S_PU_C2C_REQ_PING
{
	DWORD TICK_COUNT;
} S_PU_C2C_REQ_PING;

typedef struct _S_PU_C2C_REQ_PING_RESULT
{
	DWORD TICK_COUNT;
} S_PU_C2C_REQ_PING_RESULT;

typedef struct _S_PU_TEST
{
} S_PU_TEST;

typedef struct _S_PU_START_ARRANGEMENT
{
	PLACE_DATA PLACE_INFO[8];
} S_PU_START_ARRANGEMENT;

typedef struct _S_PU_INIT_GAME
{
	USHORT SEED;
	USHORT PLAYER_CNT;
} S_PU_INIT_GAME;

typedef struct _S_PU_TURN_DATA
{
} S_PU_TURN_DATA;

